class Solution {
public:
    ListNode* mergeTwoLists(ListNode* list1, ListNode* list2) {
        ListNode *head=NULL;
        ListNode *p=head;
        while(list1!=NULL&&list2!=NULL){
            if(list1->val<list2->val){
                if(p==NULL){
                    p=list1;
                    head=list1;
                    list1=list1->next;
                    p->next=NULL;
                }
                else{
                    p->next=list1;
                    list1=list1->next;
                    p=p->next;
                    p->next=NULL;
                }
            }
            else{
                 if(p==NULL){
                    p=list2;
                    head=list2;
                    list2=list2->next;
                    p->next=NULL;
                }
                else{
                    p->next=list2;
                    list2=list2->next;
                    p=p->next;
                    p->next=NULL;
                }
            }
        }
        while(list1!=NULL){
            if(p==NULL){
                p=list1;
                head=list1;
                list1=list1->next;
                p->next=NULL;
            }
            else{
                p->next=list1;
                list1=list1->next;
                p=p->next;
                p->next=NULL;
            }
        }
        while(list2!=NULL){
            if(p==NULL){
                p=list2;
                head=list2;
                list2=list2->next;
                p->next=NULL;
            }
            else{
                p->next=list2;
                list2=list2->next;
                p=p->next;
                p->next=NULL;
            }
        }
        return head;
    }
};
